### ISSUE TITLE
Front end: Move all CSS, JS and fonts into server

### ISSUE THREAD

**Issue by 3vcloud** [gwdevhub/GuildWarsPartySearch#57]
Leaflet and a metadata image are fetched from third parties - keep it all in the same code base by downloading and saving to disk

For google fonts, use webfont-dl on the command line - https://github.com/mmastrac/webfont-dl - only need to link "woff", omit TTF etc

**Comment by AlexMacocian** [comment]
Moved leaflet stuff onto front end. Changed the google fonts so we no longer need it
