### ISSUE TITLE
[Server] Handle explicit requests for party search list from both live feed and bot websockets

### ISSUE THREAD

**Issue by 3vcloud** [gwdevhub/GuildWarsPartySearch#76]
Add ping handling to the bot websocket, but also add a handler for something like "parties" for both websockets that executes the `GetAllPartySearches` logic and sends it back

**Comment by AlexMacocian** [comment]
Client sometimes caches the 'ping' text and sends it later with another message, like 'pingping', or 'ping{json}'. This breaks the parsing on the server.

We could rely on the `ping` `pong` message types which should be handled internally with no need for manual handling
![image](https://github.com/user-attachments/assets/42ecef58-8b38-448c-b74f-932e11954865)

**Comment by AlexMacocian** [comment]
I tried to replicate the issue through here, but I can't replicate it
https://websocketking.com/

The server handles message framing just fine. It's the client the bundles them

**Comment by AlexMacocian** [comment]
![image](https://github.com/user-attachments/assets/b1457b2f-4971-4a5f-8a58-9d4740c167d8)
Send the message with `full_list` set to `true` and the server will return you the entire list of party searches in the response

**Comment by AlexMacocian** [comment]
Works on both `live-feed` and `update` urls
