### ISSUE TITLE
use ssl in backend

### ISSUE THREAD

**Issue by DubbleClick** [gwdevhub/GuildWarsPartySearch#86]
change bots to connect to wss://party.gwtoolbox.com and configure cloudflare to forward it to caddy.
then disable the http routes in caddy.

advantages: ssl, no direct insecure connection from bots

**Comment by DubbleClick** [comment]
@3vcloud this can be configured per subdomain:
https://developers.cloudflare.com/rules/configuration-rules/

**Comment by AlexMacocian** [comment]
Can I close this @DubbleClick @3vcloud ?

**Comment by DubbleClick** [comment]
cf still redirects to http, jon has to create a configuration rule for the party subdomain
